"""Created category table.

Revision ID: 906de9770625
Revises: 36ba03f29a73
Create Date: 2024-05-26 13:55:35.181091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906de9770625'
down_revision = '36ba03f29a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
